# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlab_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='service_id',
            new_name='service',
        ),
    ]
