# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlab_api', '0003_auto_20180108_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(default='img', max_length=50),
            preserve_default=False,
        ),
    ]
