# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlab_api', '0005_user_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='phone',
            field=models.CharField(default='def', max_length=30),
            preserve_default=False,
        ),
    ]
