# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlab_api', '0008_auto_20180117_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('reserved_date', models.DateTimeField()),
            ],
        ),
    ]
