# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlab_api', '0010_auto_20180117_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBilling',
        ),
        migrations.DeleteModel(
            name='UserPlate',
        ),
    ]
