# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlab_api', '0011_auto_20180117_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('cat_name', models.CharField(max_length=100)),
                ('worker', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('ammount', models.CharField(max_length=30)),
                ('car_plate', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('reserved_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
            ],
        ),
    ]
