# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carlab_api', '0014_auto_20180117_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='sub_cat',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carlab_api.Category'),
        ),
    ]
