# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlab_api', '0017_auto_20180117_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'sub categories'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
