# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlab_api', '0018_auto_20180117_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='service',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserBilling',
        ),
        migrations.DeleteModel(
            name='UserPlate',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
